# Generated by Django 3.1.4 on 2021-01-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_temp', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermal',
            name='time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
